name: curso-django3

on: [push]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv sync --dev
          cp contrib/env-sample .env

      - name:  Rodar testes automáticos
        run: |
          pipenv run pytest pypro

      - name:  Cobertura de teste
        run: |
          pipenv run pytest --cov=pypro  

      - name:   Carregar relatórios
        run: |
          pipenv run codecov

      - name: Lint with flake8
        run: |
          pipenv run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics